version: "3.9"
services:
    backend:
        image: recipes
        container_name: recipes
        build:
            context: ./recipes
        ports:
            - "8080:80"
    frontend:
        image: recipes-ui
        container_name: recipes-ui
        build:
            context: ./recipes-fe
        ports:
            - "4200:80"
        depends_on:
            - backend